services:

  tangogql:
    platform: linux/amd64
    image: artefact.skao.int/ska-tango-tangogql-ariadne:0.1.1
    network_mode: ${NETWORK_MODE}
    depends_on:
      - tangodb
    environment:
      - TANGO_HOST=${TANGO_HOST}
    ports:
      - "5004:5004"
    restart: unless-stopped