#
# Contains services for TANGO database, database device server.
#
# Defines:
#   - tangodb: MariaDB database with TANGO schema
#   - dsconfig: Cofigures Tango device registration
#   - databaseds: TANGO database device server
#

volumes:
  tangodb: {}

services:
  tangodb:
    image: artefact.skao.int/ska-tango-images-tango-db:11.0.2
    restart: unless-stopped
    network_mode: ${NETWORK_MODE}
    container_name: tangodb
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=tango
      - MYSQL_USER=tango
      - MYSQL_PASSWORD=tango


  databaseds:
    image: artefact.skao.int/ska-tango-images-tango-databaseds:5.22.1
    restart: unless-stopped
    depends_on:
      - tangodb
    network_mode: ${NETWORK_MODE}
    container_name: databaseds
    ports:
     - "10000:10000"
    environment:
      - MYSQL_HOST=tangodb:3306
      - MYSQL_DATABASE=tango
      - MYSQL_USER=tango
      - MYSQL_PASSWORD=tango
      - TANGO_HOST=${TANGO_HOST}
    entrypoint:
      - /usr/local/bin/wait-for-it.sh
      - tangodb:3306
      - --timeout=30
      - --strict
      - --
      - /usr/local/bin/DataBaseds
      - "2"
      - -ORBendPoint
      - giop:tcp:0.0.0.0:10000

