# THIS IS NOT SUITABLE FOR PRODUCTION
version: '3'
services:
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      SWAGGER_JSON_URL: http://0.0.0.0:3000
    network_mode: ${NETWORK_MODE}
    depends_on:
      - postgrest


